# Generated by Django 5.1.7 on 2025-04-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='city',
            field=models.CharField(blank=True, choices=[('BUC', 'Bucaramanga'), ('GRN', 'Giron'), ('FLD', 'Floridablanca'), ('PDC', 'Piedecuesta')], max_length=3, null=True),
        ),
    ]
