# Generated by Django 5.1.7 on 2025-04-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_park_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Poblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('poblation', models.PositiveIntegerField()),
            ],
        ),
    ]
